# Generated by Django 3.2.16 on 2022-11-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='语境', max_length=150, verbose_name='语境')),
                ('cover_url', models.URLField(help_text='封面url', verbose_name='封面url')),
                ('video_url', models.URLField(help_text='视频url', verbose_name='视频url')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
                'db_table': 'video',
            },
        ),
    ]
