# Generated by Django 3.2.16 on 2023-01-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='context',
            field=models.CharField(default=1, help_text='真语境', max_length=30, verbose_name='真语境'),
        ),
        migrations.AddField(
            model_name='video',
            name='equation',
            field=models.CharField(default=1, help_text='公式', max_length=180, verbose_name='公式'),
        ),
        migrations.AddField(
            model_name='video',
            name='example',
            field=models.CharField(default=1, help_text='例子', max_length=200, verbose_name='例子'),
        ),
    ]
