# Generated by Django 3.2.16 on 2023-01-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20230109_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='knowledge',
            field=models.CharField(default=1, help_text='知识链接', max_length=100, verbose_name='知识链接'),
        ),
    ]
