# Generated by Django 3.2.16 on 2023-01-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_knowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default=1, help_text='真语境', max_length=30, verbose_name='真语境')),
                ('equation', models.CharField(default=1, help_text='公式', max_length=180, verbose_name='公式')),
                ('example', models.CharField(default=1, help_text='例子', max_length=200, verbose_name='例子')),
                ('cover_url', models.URLField(help_text='封面url', verbose_name='封面url')),
                ('video_url', models.URLField(help_text='视频url', verbose_name='视频url')),
                ('knowledge', models.CharField(default=1, help_text='知识链接', max_length=100, verbose_name='知识链接')),
            ],
            options={
                'verbose_name': 'mainPage',
                'verbose_name_plural': 'mainPage',
                'db_table': 'mainPage',
            },
        ),
    ]
